spring:
  application:
    name: jumbo-location-service
  profiles:
    active: local
  datasource:
    url: "jdbc:postgresql://localhost:5432/jumbo"
    username: myuser
    password: mypassword
    max-active: 15
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  config:
    import: "optional:configserver:http://localhost:8888"
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Jumbo specific configuration
jumbo:
  location:
    search:
      strategy: quadtree  # Options: quadtree, in-memory
      max-distance-km: 50  # Maximum search radius in kilometers
    stores:
      data-file: classpath:stores.json

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param

# Logging configuration
logging:
  level:
    com.jumbo: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.boot.autoconfigure: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/jumbo-location-service.log

# Management and monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  info:
    env:
      enabled: true

# API Documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
